
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/minitask?useUnicode=true&characterEncoding=utf8&useSSL=false&&serverTimezone=GMT
    username: root
    password: 123

server:
  port: 10000