
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/minitask?useUnicode=true&characterEncoding=utf8&useSSL=false&&serverTimezone=GMT
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
server:
  port: 10000